DEFAULT_OBJECTS_COLOUR = (0, 211, 134)
DEFAULT_HIDDEN_COUNT = 2
DEFAULT_SCREEN_WIDTH, DEFAULT_SCREEN_HEIGHT = 500, 500
DEFAULT_REWARD = 5

DEFAULT_TARGET_CONFIG = {
    "width": 30,
    "height": 30
}

DEFAULT_AI_MOVEMENT = {
    0: [0, -1], #UP
    1: [0, 1], #DOWN
    2: [-1, 0], #LEFT
    3: [1, 0] #RIGHT
} 